AWSTemplateFormatVersion: 2010-09-09
Description: Create ECR Repo
Parameters:
  RepositoryName:
    Type: String

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  ContainerRepository:
    Value: !Ref ECRRepository
  ContainerRepositoryArn:
    Value: !GetAtt ECRRepository.Arn